trigger:
  - master

pr:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '10.x'

  - script: npm ci
    displayName: 'Npm ci'
    workingDirectory: './js_machine_front'

  - script: npm run test
    displayName: 'Npm test'
    workingDirectory: './js_machine_front'

  - script: npm run build
    displayName: 'Npm build'
    workingDirectory: './js_machine_front'

  - task: CopyFiles@1
    displayName: 'Copy files to: $(build.artifactstagingdirectory)'
    inputs: 
     sourceFolder: '$(build.sourcesdirectory)'
     contents: |
      js_machine_front/build/**
      .firebaserc
      firebase.json
     targetFolder: '$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact: frontend.zip'
    inputs: 
      pathToPublish: '$(build.artifactstagingdirectory)'
      artifactName: 'frontend'